### ISSUE TITLE
Notes on CSS

### ISSUE THREAD

**Issue by SidTheEngineer** [pokumars/tea-cozy#2]
Overall, I don't see any major syntax issues throughout `style.css`. You've done a good job at using the tools you've gathered/learned to replicate the look and feel of the site without any major issues with the code.

Regarding your comment at the top of the file about using the local image: This could come down to the relative path we're using to pull in the image. Right now, it looks like you've got

```CSS
.mission {
  background-image: url(\resources\images\img-mission-background.jpg);
}
```

however, the `style.css` file is 2 folders deep (`/resources/css/`), so we'll need to imply that we need to look two folders up in the `resources/images` folder fort the correct image. We do this by using `../`, which implies "go up one folder". In this scenario, we can do:

```CSS
.mission {
  background-image: url(../../resources/images/img-mission-background.jpg);  
}
```

Another area we can adjust throughout the styling is the font. All of the font throughout the site should be `Helvetica`. See if you can make this change using a selector in your CSS.

Lastly, the title of the locations section of the site should be within the locations block (above "Downtown", "East Bayside",  and "Oakdale", over the background image). Here is an example of what that looks like:

<img width="1219" alt="screen shot 2018-07-10 at 1 18 00 am" src="https://user-images.githubusercontent.com/19176417/42490567-1e10ec38-83df-11e8-920b-808eb7b1895b.png">
